<?php
    include 'app/models/User.php';
    $User = new User;
    $rowFindUser = $User->find( ( isset( $_GET[ 'id' ] ) ? $_GET[ 'id' ] : '' ) );
?>

<h1>Editing User</h1><br/>

<form id="formEditUser" data-action="edit">
    <input type="hidden" name="id" value="<?php echo $rowFindUser[ 'id' ] ?>">
    <div>
        <label for="username">Username</label><br/>
        <input type="text" name="username" id="username" onchange="checkUserOrEmail( $( this ) )" value="<?php echo $rowFindUser[ 'username' ] ?>">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <label for="email">Email</label><br/>
        <input type="email" name="email" id="email" onchange="checkUserOrEmail( $( this ) )" value="<?php echo $rowFindUser[ 'email' ] ?>">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <input type="submit" class="btn btn-success" value="Save">
        <a href="?section=users&page=edit-password&id=<?php echo $rowFindUser[ 'id' ] ?>" class="btn btn-danger">Change Password</a>
        <a href="index.php" class="btn btn-inverse">Back</a>
    </div>
</form>