<?php
    include 'app/models/User.php';
    $User = new User;
    $rowFindUser = $User->find( ( isset( $_GET[ 'id' ] ) ? $_GET[ 'id' ] : '' ) );
?>

<h1>Change Password</h1><br/>

<form id="formEditUser" data-action="edit-password">
    <input type="hidden" name="id" value="<?php echo $rowFindUser[ 'id' ] ?>">
    <div>
        <label for="password">Password</label><br/>
        <input type="password" name="password" id="password">
    </div><br/>
    <div>
        <label for="re-password">Confirm Password</label><br/>
        <input type="password" name="re-password" id="re-password">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <input type="submit" class="btn btn-success" value="Save new password">
        <a href="?section=users&page=edit&id=<?php echo $rowFindUser[ 'id' ] ?>" class="btn btn-inverse">Back</a>
    </div>
</form>