<?php 
    include 'app/models/User.php'; 
    $User = new User;
    $findAllUsers = $User->find( null, array( 'many?' => true ) );
?>

<h1>CRUD List Users</h1><br/>

<a href="?section=users&page=new" class="btn btn-success">Create User</a><br/><br/>

<table class="table table-condesed table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Password (Encrypted)</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            if ( !is_null( $findAllUsers ) ) {
                while ( $rowFindUser = $findAllUsers->fetch_assoc() ) {
        ?>
        <tr>
            <td><?php echo $rowFindUser[ 'id' ]; ?></td>
            <td><?php echo $rowFindUser[ 'username' ]; ?></td>
            <td><?php echo $rowFindUser[ 'password' ]; ?></td>
            <td><?php echo $rowFindUser[ 'email' ]; ?></td>
            <td>
                <a href="?section=users&page=show&id=<?php echo $rowFindUser[ 'id' ] ?>" class="btn btn-info">Show</a>
                <a href="?section=users&page=edit&id=<?php echo $rowFindUser[ 'id' ] ?>" class="btn btn-warning">Edit</a>
                <button data-id="<?php echo $rowFindUser[ 'id' ] ?>" class="btn btn-danger" onclick="destroyUser( $( this ) )">Destroy</button>
            </td>
        </tr>
        <?php
                }
            } else {
        ?>
        <tr>
            <td colspan="5" class="emptyUsers">No hay Usuarios registrados</td>
        </tr>
        <?php
            }
        ?>
    </tbody>
</table>