<h1>New User</h1><br/>

<form id="formNewUser" data-action="new">
    <div>
        <label for="username">Username</label><br/>
        <input type="text" name="username" id="username" onchange="checkUserOrEmail( $( this ) )">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <label for="password">Password</label><br/>
        <input type="password" name="password" id="password">
    </div><br/>
    <div>
        <label for="re-password">Confirm Password</label><br/>
        <input type="password" name="re-password" id="re-password">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <label for="email">Email</label><br/>
        <input type="email" name="email" id="email" onchange="checkUserOrEmail( $( this ) )">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <input type="submit" class="btn btn-success" value="Save">
        <a href="index.php" class="btn btn-inverse">Back</a>
    </div>
</form>